// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loans.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLoanByID = `-- name: GetLoanByID :one
SELECT uuid, borrower_uuid, amount_idr, term_months, loan_type, interest_rate_apr, status, created_at, updated_at, officer_uuid, assigned_to_uuid FROM loans WHERE uuid = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, argUuid uuid.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, argUuid)
	var i Loan
	err := row.Scan(
		&i.Uuid,
		&i.BorrowerUuid,
		&i.AmountIdr,
		&i.TermMonths,
		&i.LoanType,
		&i.InterestRateApr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfficerUuid,
		&i.AssignedToUuid,
	)
	return i, err
}

const saveLoan = `-- name: SaveLoan :exec
INSERT INTO loans (uuid, borrower_uuid, officer_uuid, amount_idr, term_months, loan_type, interest_rate_apr, status, created_at, updated_at, assigned_to_uuid)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (uuid) DO UPDATE
SET assigned_to_uuid = EXCLUDED.assigned_to_uuid,
    updated_at = EXCLUDED.updated_at
`

type SaveLoanParams struct {
	Uuid            uuid.UUID
	BorrowerUuid    uuid.UUID
	OfficerUuid     uuid.UUID
	AmountIdr       int64
	TermMonths      int32
	LoanType        string
	InterestRateApr float64
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AssignedToUuid  uuid.UUID
}

func (q *Queries) SaveLoan(ctx context.Context, arg SaveLoanParams) error {
	_, err := q.db.Exec(ctx, saveLoan,
		arg.Uuid,
		arg.BorrowerUuid,
		arg.OfficerUuid,
		arg.AmountIdr,
		arg.TermMonths,
		arg.LoanType,
		arg.InterestRateApr,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AssignedToUuid,
	)
	return err
}
