name: 'pinjamean'
services:
  loans-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "127.0.0.1:7777:7777"
    env_file:
      - .env
    environment:
      SERVICE: loans
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
