// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Loan struct {
	Uuid            uuid.UUID
	BorrowerUuid    uuid.UUID
	AmountIdr       int64
	TermMonths      int32
	LoanType        string
	InterestRateApr float64
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	Uuid           uuid.UUID
	Email          string
	Passwordhashed string
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
