// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT uuid, email, passwordhashed, role, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Passwordhashed,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveAccount = `-- name: SaveAccount :exec
INSERT INTO users (uuid, email, passwordHashed, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveAccountParams struct {
	Uuid           uuid.UUID
	Email          string
	Passwordhashed string
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) SaveAccount(ctx context.Context, arg SaveAccountParams) error {
	_, err := q.db.Exec(ctx, saveAccount,
		arg.Uuid,
		arg.Email,
		arg.Passwordhashed,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
