// Package ports provides generated models for the identity login API.
// Code generated by github.com/oapi-codegen/oapi-codegen/v2. DO NOT EDIT.
package ports

import openapi_types "github.com/oapi-codegen/runtime/types"

// LoginRequest is the request body for POST /auth/login.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string             `json:"password"`
}

// LoginResponse is the successful response for POST /auth/login.
type LoginResponse struct {
	AccessToken string `json:"accessToken"`
	TokenType   string `json:"tokenType"`
}
