// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ports

// Defines values for PostApplicationsLoanType.
const (
	KKB PostApplicationsLoanType = "KKB"
	KMG PostApplicationsLoanType = "KMG"
	KMK PostApplicationsLoanType = "KMK"
	KPR PostApplicationsLoanType = "KPR"
	KTA PostApplicationsLoanType = "KTA"
	KUR PostApplicationsLoanType = "KUR"
)

// Valid indicates whether the value is a known member of the PostApplicationsLoanType enum.
func (e PostApplicationsLoanType) Valid() bool {
	switch e {
	case KKB:
		return true
	case KMG:
		return true
	case KMK:
		return true
	case KPR:
		return true
	case KTA:
		return true
	case KUR:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Message Human-readable error description.
	Message string `json:"message"`

	// Slug Machine-readable error code (e.g., invalid-loan-parameters).
	Slug string `json:"slug"`
}

// PostApplications defines model for PostApplications.
type PostApplications struct {
	// BorrowerId Unique identifier for the applicant.
	BorrowerId string `json:"borrower_id"`

	// LoanAmountIdr Total loan amount requested in Indonesian Rupiah (IDR).
	LoanAmountIdr int `json:"loan_amount_idr"`

	// LoanType The category of the loan based on standard Indonesian lending products.
	LoanType PostApplicationsLoanType `json:"loan_type"`

	// TermMonths Duration of the loan in months.
	TermMonths int `json:"term_months"`
}

// PostApplicationsLoanType The category of the loan based on standard Indonesian lending products.
type PostApplicationsLoanType string

// SubmitApplicationJSONRequestBody defines body for SubmitApplication for application/json ContentType.
type SubmitApplicationJSONRequestBody = PostApplications
