// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ports

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LoanType.
const (
	KKB LoanType = "KKB"
	KMG LoanType = "KMG"
	KMK LoanType = "KMK"
	KPR LoanType = "KPR"
	KTA LoanType = "KTA"
	KUR LoanType = "KUR"
)

// Valid indicates whether the value is a known member of the LoanType enum.
func (e LoanType) Valid() bool {
	switch e {
	case KKB:
		return true
	case KMG:
		return true
	case KMK:
		return true
	case KPR:
		return true
	case KTA:
		return true
	case KUR:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// LoanResponse defines model for LoanResponse.
type LoanResponse struct {
	AmountIdr       int64              `json:"amountIdr"`
	BorrowerUuid    openapi_types.UUID `json:"borrowerUuid"`
	InterestRateApr float32            `json:"interestRateApr"`
	LoanType        LoanType           `json:"loanType"`
	Status          string             `json:"status"`
	TermMonths      int                `json:"termMonths"`
	Uuid            openapi_types.UUID `json:"uuid"`
}

// LoanType defines model for LoanType.
type LoanType string

// SubmitLoanRequest defines model for SubmitLoanRequest.
type SubmitLoanRequest struct {
	AmountIdr    int64              `json:"amountIdr"`
	BorrowerUuid openapi_types.UUID `json:"borrowerUuid"`
	LoanType     LoanType           `json:"loanType"`
	TermMonths   int                `json:"termMonths"`
}

// SubmitLoanJSONRequestBody defines body for SubmitLoan for application/json ContentType.
type SubmitLoanJSONRequestBody = SubmitLoanRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SubmitLoan Submit a new loan application
	// (POST /loans)
	SubmitLoan(w http.ResponseWriter, r *http.Request)
	// GetLoanByUuid Get loan by loan's UUID
	// (GET /loans/{uuid})
	GetLoanByUuid(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// SubmitLoan Submit a new loan application
// (POST /loans)
func (_ Unimplemented) SubmitLoan(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLoanByUuid Get loan by loan's UUID
// (GET /loans/{uuid})
func (_ Unimplemented) GetLoanByUuid(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubmitLoan operation middleware
func (siw *ServerInterfaceWrapper) SubmitLoan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitLoan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLoanByUuid operation middleware
func (siw *ServerInterfaceWrapper) GetLoanByUuid(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", chi.URLParam(r, "uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLoanByUuid(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/loans", wrapper.SubmitLoan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/loans/{uuid}", wrapper.GetLoanByUuid)
	})

	return r
}

type SubmitLoanRequestObject struct {
	Body *SubmitLoanJSONRequestBody
}

type SubmitLoanResponseObject interface {
	VisitSubmitLoanResponse(w http.ResponseWriter) error
}

type SubmitLoan204Response struct {
}

func (response SubmitLoan204Response) VisitSubmitLoanResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SubmitLoan400JSONResponse ErrorResponse

func (response SubmitLoan400JSONResponse) VisitSubmitLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetLoanByUuidRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetLoanByUuidResponseObject interface {
	VisitGetLoanByUuidResponse(w http.ResponseWriter) error
}

type GetLoanByUuid200JSONResponse LoanResponse

func (response GetLoanByUuid200JSONResponse) VisitGetLoanByUuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLoanByUuid404JSONResponse ErrorResponse

func (response GetLoanByUuid404JSONResponse) VisitGetLoanByUuidResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// SubmitLoan Submit a new loan application
	// (POST /loans)
	SubmitLoan(ctx context.Context, request SubmitLoanRequestObject) (SubmitLoanResponseObject, error)
	// GetLoanByUuid Get loan by loan's UUID
	// (GET /loans/{uuid})
	GetLoanByUuid(ctx context.Context, request GetLoanByUuidRequestObject) (GetLoanByUuidResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// SubmitLoan operation middleware
func (sh *strictHandler) SubmitLoan(w http.ResponseWriter, r *http.Request) {
	var request SubmitLoanRequestObject

	var body SubmitLoanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitLoan(ctx, request.(SubmitLoanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitLoan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitLoanResponseObject); ok {
		if err := validResponse.VisitSubmitLoanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLoanByUuid operation middleware
func (sh *strictHandler) GetLoanByUuid(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetLoanByUuidRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLoanByUuid(ctx, request.(GetLoanByUuidRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLoanByUuid")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLoanByUuidResponseObject); ok {
		if err := validResponse.VisitGetLoanByUuidResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
